#!/usr/bin/env python3
"""Render measured results and freeze conditional predictions for later collation."""
import hashlib
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent


def main():
    raw = (HERE / "results.json").read_bytes()
    result = json.loads(raw)
    s = result["summary"]
    family = "transpose_and_half_turn"
    predictions = {
        "created": "2026-09-16", "assumption": family,
        "source_corpus_sha256": result["input_sha256"],
        "results_sha256": hashlib.sha256(raw).hexdigest(),
        "status": "conditional, unvalidated; zero-based row and column",
        "blindness": "Not a blind experiment. Peterson variants and Kollatsch examples were retrieved during discovery. A future test needs an exposure audit.",
        "squares": [{"id": square["id"],
                     "fills": square["symmetry"][family]["conditional_fills"],
                     "free_orbits": square["symmetry"][family]["free_orbits"]}
                    for square in result["squares"]
                    if square["blank_cells"] and square["symmetry"][family]["compatible"]],
    }
    (HERE / "predictions.json").write_text(json.dumps(predictions, indent=2) + "\n")
    lines = ["# First Mathers structural pass", "", "Generated by `report.py`; counts apply to the pinned digital row export, not a manuscript.", "",
             f"Extracted **{s['source_records']} records**. Analyzed **{s['analyzed']}**: "
             f"**{s['complete']} complete**, **{s['incomplete']} incomplete**. "
             f"Excluded **{len(s['excluded'])}** ambiguous layouts without correction.", "",
             f"The analyzed grids contain **{s['known_cells']} letters** and **{s['blank_cells']} blanks**.", "",
             "## Exact symmetry", "",
             "| Assumed symmetry | Complete grids satisfying it | Compatible incomplete grids | Forced blank cells in compatible grids |",
             "|---|---:|---:|---:|"]
    for f, count in s["complete_exact_symmetry"].items():
        inc = s["incomplete_symmetry"][f]
        lines.append(f"| {f} | {count}/{s['complete']} | {inc['compatible_grids']}/{s['incomplete']} | {inc['conditional_fills_in_compatible_grids']} |")
    lines += ["", "Compatibility can be vacuous when few letters are present. Forced cells are conditional on the rule; they are not authenticated readings. Counts across families overlap and must not be added.", "",
              "## Elementary generators", "",
              f"Fixed-step cyclic row generators: **{s['complete_fixed_cyclic']}/{s['complete']}** exact fits. "
              f"Even allowing a separately chosen rotation for each row: **{s['complete_arbitrary_row_rotations']}/{s['complete']}**.", "",
              "Exact boundary-arithmetic fits (A=0, modulo 26): " + "; ".join(f"`{k}`: {v}/{s['complete']}" for k, v in s["complete_boundary_affine"].items()) + ".", "",
              "This rejects those exact families in this export. It does not rule out other alphabets, richer generators, or witness corruption.", "",
              "## Masking diagnostic on complete grids", "",
              "Keep only the top row and left column of each complete grid, then predict the rest. Rules are fixed; no grid is selected using its hidden answers. This is within-transcription validation, not independent witness validation.", "",
              "| Rule | Hidden cells | Predictions | Correct | Wrong | Abstained | Visible-mode correct on same predicted cells |",
              "|---|---:|---:|---:|---:|---:|---:|"]
    for f, d in s["masked_complete_grid_diagnostic"].items():
        lines.append(f"| {f} | {d['hidden']} | {d['predicted']} | {d['correct']} | {d['wrong']} | {d['abstained']} | {d['visible_mode_correct_on_predictions']} |")
    m = s["maiam_25_3_example"]
    lines += ["", "Transpose symmetry alone cannot infer interior letters from that boundary. The frequency baseline selects the most frequent visible letter, with alphabetical tie-breaking; it is compared on the identical cells. No claim of statistical significance is made.", "",
              "## MAIAM: why symmetry is not a generator", "",
              f"Mathers 25/3 has {m['known']} known cells and {m['blank']} blanks. "
              f"Transpose plus half-turn forces {m['conditional_fills']} letters but leaves "
              f"{m['free_orbits']} free letter orbits: **{m['compatible_completions_over_A_Z']:,}** "
              "completions over A–Z satisfy those symmetries. No language constraints were imposed.", "",
              "## Layout exclusions", ""]
    lines += [f"- {e['id']}: {e['reason']}" for e in s["excluded"]]
    lines += ["", "## Files and limits", "",
              "`results.json` records every per-square contradiction, free orbit and conditional fill. "
              "`predictions.json` freezes the transpose-plus-half-turn fills with input hashes. "
              "No German image comparison has run. Source numbering, letter case, multi-letter cells and missing delimiters need facsimile checks.", ""]
    (HERE / "RESULTS.md").write_text("\n".join(lines))


if __name__ == "__main__":
    main()
