#!/usr/bin/env python3
"""Regenerate catalog/INDEX.md from the entries.

Weights live here and only here. `classic` is the reader's "greatest unsolved
text"; `attackable` adds the axes that say whether we could make progress.
"""
from __future__ import annotations

import argparse
import re
from datetime import date

from catalog_lib import ROOT, AXES, Entry, load_all

# Statuses kept out of the live rankings and shown as a calibration set.
CALIBRATION = {"solved", "likely-hoax", "likely-noise"}

WEIGHTS = {
    "classic":    {"mystery": 1, "material": 1, "solvable": 1},
    "attackable": {"mystery": 1, "material": 1, "solvable": 1,
                   "compute": 2, "verifiable": 1, "crowding": 0.5},
}


def composite(e: Entry, name: str) -> float:
    return sum(w * e.score(axis) for axis, w in WEIGHTS[name].items())


def max_for(name: str) -> float:
    return 5 * sum(WEIGHTS[name].values())


def fmt_weights(name: str) -> str:
    return " + ".join(f"{w:g}·{axis}" if w != 1 else axis for axis, w in WEIGHTS[name].items())


SECTION_RE = re.compile(r"^##\s+What is unsolved\s*$(.*?)(?=^##\s|\Z)", re.M | re.S)
SENTENCE_END = re.compile(r"(?<=[.!?])\s+(?=[A-Z\u00C0-\u024F\"“(])")


def open_question(e: Entry, limit: int = 300) -> str:
    """First sentence of the entry's 'What is unsolved' section, de-markdowned."""
    m = SECTION_RE.search(e.body)
    if not m:
        return ""
    text = " ".join(line.strip().lstrip("-* ") for line in m.group(1).strip().splitlines() if line.strip())
    text = re.sub(r"\*\*?([^*]+)\*\*?", r"\1", text)
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
    text = re.sub(r"`([^`]+)`", r"\1", text)
    sentences = SENTENCE_END.split(text)
    first = sentences[0].strip()
    # A terse opening sentence ("The cipher system.") gets its follow-up.
    if len(first) < 90 and len(sentences) > 1:
        first = f"{first} {sentences[1].strip()}"
    if len(first) > limit:
        first = first[: limit - 1].rsplit(" ", 1)[0] + "…"
    return first


AXIS_LETTER = {"mystery": "M", "material": "S", "solvable": "R", "compute": "C", "verifiable": "V", "crowding": "K"}


def scoreline(e: Entry) -> str:
    return " ".join(f"{AXIS_LETTER[a]}{e.score(a)}" for a in AXES)


def render_readable(entries: list[Entry]) -> str:
    live = [e for e in entries if e.meta.get("status") not in CALIBRATION]
    calib = [e for e in entries if e.meta.get("status") in CALIBRATION]
    by_attack = sorted(live, key=lambda e: (-composite(e, "attackable"), -composite(e, "classic"), e.slug))
    by_classic = sorted(live, key=lambda e: (-composite(e, "classic"), -composite(e, "attackable"), e.slug))

    out = ["# Rankings", ""]
    out.append(f"Generated by `scripts/rank.py` on {date.today().isoformat()} from {len(live)} live entries in "
               f"`catalog/entries/`. Do not edit by hand; edit an entry's scores and rerun.")
    out.append("")
    out.append("Two orderings. **Attackable** asks where a modern effort could plausibly make progress: "
               f"{fmt_weights('attackable')} (max {max_for('attackable'):g}). **Classic** is the reader's "
               f"\"greatest unsolved text\": {fmt_weights('classic')} (max {max_for('classic'):g}). "
               "Scores are 1–5 per axis, defined in `rubric/RUBRIC.md`: "
               "**M**ystery, **S**urviving material, **R**eally solvable, **C**ompute, **V**erifiable, "
               "**K**rowding (higher = emptier field). ⚠ marks an entry whose scorer rated their own confidence low.")
    out.append("")
    out.append("## Ranked by attackable")
    out.append("")
    for i, e in enumerate(by_attack, 1):
        flag = " ⚠" if e.meta.get("confidence") == "low" else ""
        meta = e.meta
        out.append(f"{i}. **[{meta.get('title', e.slug)}](catalog/entries/{e.slug}.md)**{flag} "
                   f"· {meta.get('kind','')} · {meta.get('status','')} · {meta.get('era','')}  ")
        q = open_question(e)
        out.append(f"   {q}  " if q else "   ")
        out.append(f"   `{scoreline(e)}` → attackable **{composite(e, 'attackable'):g}**, classic {composite(e, 'classic'):g}")
        out.append("")
    out.append("## Ranked by classic")
    out.append("")
    for i, e in enumerate(by_classic, 1):
        flag = " ⚠" if e.meta.get("confidence") == "low" else ""
        out.append(f"{i}. [{e.meta.get('title', e.slug)}](catalog/entries/{e.slug}.md){flag} — "
                   f"classic **{composite(e, 'classic'):g}**, attackable {composite(e, 'attackable'):g}")
    out.append("")
    out.append("## Calibration cases")
    out.append("")
    out.append("Solved, hoax, and noise cases kept so the rubric can be checked against known outcomes. "
               "Not ranked.")
    out.append("")
    for e in sorted(calib, key=lambda e: (e.meta.get("status", ""), e.slug)):
        out.append(f"- [{e.meta.get('title', e.slug)}](catalog/entries/{e.slug}.md) · {e.meta.get('status','')} · "
                   f"`{scoreline(e)}` → attackable {composite(e, 'attackable'):g}")
    out.append("")
    return "\n".join(out)


def render(entries: list[Entry]) -> str:
    live = [e for e in entries if e.meta.get("status") not in CALIBRATION]
    solved = [e for e in entries if e.meta.get("status") in CALIBRATION]
    by_attack = sorted(live, key=lambda e: (-composite(e, "attackable"), -composite(e, "classic"), e.slug))
    by_classic = sorted(live, key=lambda e: (-composite(e, "classic"), -composite(e, "attackable"), e.slug))

    out: list[str] = []
    out.append("# Catalog index\n")
    out.append(f"Generated by `scripts/rank.py` on {date.today().isoformat()}. Do not edit by hand.\n")
    out.append(f"- **classic** = {fmt_weights('classic')} (max {max_for('classic'):g})")
    out.append(f"- **attackable** = {fmt_weights('attackable')} (max {max_for('attackable'):g})")
    out.append(f"- {len(live)} live entries, {len(solved)} calibration entries (solved, likely-hoax, likely-noise). "
               f"Entries marked ⚠ are `confidence = \"low\"`.\n")

    def table(rows: list[Entry], primary: str) -> list[str]:
        head = ["#", "Entry", "Kind", "Status", "Classic", "Attackable"] + [a[:4] for a in AXES]
        lines = ["| " + " | ".join(head) + " |", "|" + "---|" * len(head)]
        for i, e in enumerate(rows, 1):
            flag = " ⚠" if e.meta.get("confidence") == "low" else ""
            title = f"[{e.meta.get('title', e.slug)}](entries/{e.slug}.md){flag}"
            cells = [str(i), title, e.meta.get("kind", ""), e.meta.get("status", ""),
                     f"{composite(e, 'classic'):g}", f"{composite(e, 'attackable'):g}"]
            cells += [str(e.score(a)) for a in AXES]
            lines.append("| " + " | ".join(cells) + " |")
        return lines

    out.append("## Ranked by attackable\n")
    out += table(by_attack, "attackable")
    out.append("\n## Ranked by classic\n")
    out += table(by_classic, "classic")
    if solved:
        out.append("\n## Calibration cases (solved, likely-hoax, likely-noise)\n")
        out += table(sorted(solved, key=lambda e: e.slug), "attackable")

    # Kind and status breakdowns
    out.append("\n## Breakdown\n")
    kinds: dict[str, int] = {}
    statuses: dict[str, int] = {}
    for e in entries:
        kinds[e.meta.get("kind", "?")] = kinds.get(e.meta.get("kind", "?"), 0) + 1
        statuses[e.meta.get("status", "?")] = statuses.get(e.meta.get("status", "?"), 0) + 1
    out.append("By kind: " + ", ".join(f"{k} {v}" for k, v in sorted(kinds.items())))
    out.append("\nBy status: " + ", ".join(f"{k} {v}" for k, v in sorted(statuses.items())))
    return "\n".join(out) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--top", type=int, help="print the top N by attackable to stdout instead of writing INDEX.md")
    ap.add_argument("--by", choices=list(WEIGHTS), default="attackable")
    args = ap.parse_args()
    entries = load_all()
    if args.top:
        live = [e for e in entries if e.meta.get("status") not in CALIBRATION]
        for i, e in enumerate(sorted(live, key=lambda e: -composite(e, args.by))[: args.top], 1):
            print(f"{i:3d}  {composite(e, args.by):5g}  {e.meta.get('title', e.slug)}")
        return
    (ROOT / "catalog" / "INDEX.md").write_text(render(entries), encoding="utf-8")
    (ROOT / "RANKINGS.md").write_text(render_readable(entries), encoding="utf-8")
    print(f"wrote catalog/INDEX.md and RANKINGS.md ({len(entries)} entries)")


if __name__ == "__main__":
    main()
