#!/usr/bin/env python3
"""Render the readable Dresden N 111 Book IV packet from the committed readings. Presentation only.

python3 collation.py            write COLLATION.md
python3 collation.py --check    verify it reproduces
"""
import json, sys
from pathlib import Path

HERE = Path(__file__).resolve().parent


def rows_for(a, b):
    if a and b and list(map(len, a)) == list(map(len, b)):
        return ["".join(x if x == y else "?" for x, y in zip(ra, rb)) for ra, rb in zip(a, b)], None
    return None, (a, b)


def main():
    inv = json.load(open(HERE / "inventory.json"))
    index = {p["physical_page"]: p for p in json.load(open(HERE / "image-manifest.json"))["images"]}
    reads = {}
    for reader in "AB":
        for f in sorted((HERE / "readings" / reader).glob("R*.json")):
            for it in json.load(open(f))["items"]:
                reads.setdefault(it["locator_id"], {})[reader] = [r.upper() for r in it.get("rows") or []]
    lines = ["# Dresden N 111, Book IV, physical pages 246–272 — double-keyed reading packet", "",
             "Generated by `collation.py` from the committed locator inventory and the two",
             "independent Opus readings. A letter is shown where readers A and B agree;",
             "`?` marks a conflict or a cell either reader could not read. Nothing is",
             "repaired. Item numbers and headings are as the locators read them. PRIMARY —",
             "[SLUB record](https://digital.slub-dresden.de/id364474017).", ""]
    for g in inv["grids"]:
        page = index[g["physical_page"]]
        ident = f"IV.{g.get('chapter')}.{g.get('item') if g.get('item') is not None else '(unnumbered)'}"
        lines += [f"## {g['locator_id']} — {ident}", "",
                  f"Physical {g['physical_page']} (label {page['page_label']}), column {g['column']}, "
                  f"grid {g['index']}. [Page image]({page['original_image']}). Heading: “{g.get('short_heading')}”", ""]
        r = reads.get(g["locator_id"], {})
        rows, both = rows_for(r.get("A"), r.get("B"))
        if rows is not None:
            lines += ["```text", *(" ".join(row) for row in rows), "```", ""]
        else:
            lines += ["Readers disagree on shape.", "", "```text", "A:", *both[0], "B:", *both[1], "```", ""]
        if g.get("note"):
            lines += [f"Locator note: {g['note']}", ""]
    text = "\n".join(lines).rstrip() + "\n"
    path = HERE / "COLLATION.md"
    if "--check" in sys.argv:
        assert path.read_text() == text, "COLLATION.md differs"
        print("collation reproduces")
        return
    path.write_text(text)
    print(len(inv["grids"]), "grids rendered")


if __name__ == "__main__":
    main()
